spring:
  application:
    name: chat-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/chatdb
    username: root
    password: password
    #driver-class-name: com.mysql.cj.jdbc.Driver
    # Driver not needed
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    com.underarmour.interview.chat: DEBUG

server:
  port: 9000

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
